config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  # root для главной страницы root
  root 'posts#index', as: 'home'

  # для остальных страниц get
  get 'about' => 'pages#about', as: 'about'

  resources :users

  # для отслежсивания юрл адрессов create, new, update, delete и других
  resources :posts do
    resources :comments
  end

  namespace :admin do
    resources
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :image, ImageUploader

  belongs_to :user

  has_many :comments

  validates :title, presence: true, length: {minimum: 5}

  public def short_body(body)
    body = "edited"
  end

end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :image, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # http_basic_authenticate_with name: 'admin', password: 'admin', except: [:index, :show]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/concerns/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    edit_user_path(resource)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Page about us!'
    @text = 'Some text for example.'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # http_basic_authenticate_with name: 'admin', password: 'admin', except: [:index, :show]

  def index
    @post = Post.all
    # unless @post.nil?
    #   @post.each do |post|
    #     post.body = post.body[0, 100] + '...' if post.body.size > 100
    #   end
    # end
  end

  def new
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end

  def create
    # render plain: params[:post].inspect
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  private def post_params
    params.require(:post).permit(:title, :body, :time, :end_time, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @index = 0
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private def user_params
    params.require(:user).permit(:email, :name, :surname, :nickname, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleProject</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
    nav a {
      color: gray;
    }

    .img-avatar-nav {
      border-radius: 5px;
      max-height: 40px;
    }

    .img-avatar {
      border-radius: 20px;
    }
    .body-text{
      font-size: 14px;
      text-align: justify;
    }
  </style>

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Funny TIME</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

  </div>

  <% if !current_user.nil? && current_user.image? %>
    <%= image_tag current_user.image.url(:thumb), class: 'img-avatar-nav mr-5 shadow' %>
  <% end %>

</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li>
            <span class="py-2 d-none d-md-inline-block link-to"><%= link_to "Главная страница", home_path %></span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Календарь событий (не работает)
            </a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <span class="nav-link py-2 d-none d-md-inline-block"><%= link_to "Новое событие", new_post_path %></span>
            </li>
            <li class="nav-item">
              <span class="nav-link py-2 d-none d-md-inline-block"><%= link_to "Личный кабинет", user_path(current_user) %></span>
            </li>
            <li class="nav-item">
              <span class="py-2 d-none d-md-inline-block"><%= link_to "Выход", destroy_user_session_path, method: :delete %></span>
            </li>
          <% else %>
            <li class="nav-item">
              <span class="py-2 d-none d-md-inline-block"><%= link_to "Вход", new_user_session_path %></span>
            </li>
            <li class="nav-item">
              <span class="py-2 d-none d-md-inline-block"><%= link_to "Регистрация", new_user_registration_path %></span>
            </li>
          <% end %>
          <li class="nav-item">
            <span class="py-2 d-none d-md-inline-block"><%= link_to "О проекте", about_path %></span>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <%= yield %>
    </main>
  </div>
</div>

<!--<footer class="footer py-3 fixed-bottom">-->

<!--    <span class="text-muted">Place sticky footer content here.</span>-->

<!--</footer>-->

</body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>
<p><%= @text %></p>

app/views/posts/edit.html.erb
<h2>Edit post</h2>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col">
      <p>
        Заголовок<br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
      </p>

      <p>
        Описание<br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
      </p>

      <p>
        Дата и время начала<br>
        <%= f.datetime_select(:time, {:class => 'custom-select'}) %>
      </p>

      <p>
        Дата и время окончания<br>
        <%= f.datetime_select(:end_time, {:class => 'custom-select'}) %>
      </p>

      <p>
        Изображение<br>
        <%= f.file_field :image %>
      </p>

      <p>
        <%= f.submit({:class => 'btn btn-dark'}) %>
      </p>
    </div>
  </div>

<% end %>

app/views/posts/index.html.erb
<br>

<% @post.each_with_index do |post, index| %>


  <% if index % 3 == 0 %>
    <!--  Row-->
    <div class="row">
  <% end %>

  <!--  Col-->
  <div class="col-4 mb-4">
    <div class="card ml-2 shadow" style="width: 320px; height: 700px;">
      <% if post.image? %>
        <%= image_tag post.image.url(:large), class: "card-img rounded" %>
      <% else %>
        <img src="http://i66.tinypic.com/hunnlw.jpg" class="card-img rounded" alt="...">
      <% end %>
      <div class="card-body">
        <h5 class="card-title font-weight-bold"><%= post.title %></h5>
        <hr>
        <p class="body-text h6 font-italic"><%= post.body %></p>
        <hr>
        <p class="mb-1">
          <img src="https://cdn1.imggmi.com/uploads/2019/4/28/74f9da038a0b70ba18ac521d2556c1ca-full.png" border="0"/>
          <small class="text-muted"><%= post.end_time.strftime "%d-%m-%Y" %></small>
        </p>
        <p class="card-text">
          <img src="https://cdn1.imggmi.com/uploads/2019/4/28/91a22c46cbae88fac5a3d0f7ee0df818-full.png" border="0"/>
          <small class="text-muted"><%= post.time.strftime "%H:%M" %>-<%= post.end_time.strftime "%H:%M" %></small><br>
        </p>
        <hr>
        <small class="text-muted">Автор: <%= User.find(post.user_id).email %></small>
        <br>
        <small class="text-muted">Создан: <%= post.created_at.strftime "%Y-%m-%d" %></small>
        <br>
        <small class="text-muted">Обновлен: <%= post.updated_at.strftime "%Y-%m-%d %H:%M:%S" %></small>
      </div>
      <div class="card-footer bg-transparent">
        <% if user_signed_in? %>
          <a class="text-decoration-none" href="<%= post_path(post) %>">Подробнее...</a>
        <% end %>
      </div>
    </div>
  </div>

  <% if (index + 1) % 3 == 0 %>
    <!--  End Row-->
    </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h2>Create new post</h2>

<%= form_for :post, url: posts_path, html: { multipart: true } do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    Название события<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    Описание события<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    Дата и время начала<br>
    <%= f.datetime_select(:time, {:class => 'custom-select'}) %>
  </p>

  <p>
    Дата и время окончания<br>
    <%= f.datetime_select(:end_time, {:class => 'custom-select'}) %>
  </p>

  <p>
    Изображение<br>
    <%= f.file_field(:image, {:class => 'custom-file'} )%>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-dark'}) %>
  </p>

<% end %>

app/views/posts/show.html.erb
<br>
<div class="row">
  <%= image_tag @post.image.url(:large) %>
  <div class="col">
    <h2><%= @post.title %></h2>
    <h5><%= @post.body %></h5>
    <h5>Стартуем в <%= @post.time %></h5>
    <h5>Заканчиваем в <%= @post.end_time %></h5>
  </div>
</div>

<% if current_user.admin || current_user.id == @post.user_id %>
  <hr>
  <%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-warning' %>
  <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Вы уверены, что хотите удалить этот пост?"}, :class => 'btn btn-danger' %>
  <hr>
<% end %>

<h2>All comments:</h2>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <p><strong><%= comment.username %>:</strong> <%= comment.body %></p>
  </div>
<% end %>
<hr>

<h2>Create new comment</h2>

<%= form_for([@post, @post.comments.build]) do |f| %>

  <%# if @post.errors.any? %>
  <%# @post.errors.full_messages.each do |msg| %>
  <!--      <div class="alert alert-danger"><%#= msg %></div>-->
  <%# end %>
  <%# end %>

  <p>
    User<br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>

  <p>
    Text<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit("Create new comment", {:class => 'btn btn-success'}) %>
  </p>

<% end %>

app/views/users/edit.html.erb
<% if !@user.nickname.nil? %>
  <% nick = @user.nickname %>
<% else %>
  <% nick = @user.email %>
<% end %>

<h1>Congrat! <%= nick %></h1>

<%= form_for :user, url: user_path(@user), method: :patch do |f| %>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    email<br>
    <%= f.text_field(:email, {:class => 'form-control'}) %>
  </p>

  <p>
    Ник (если не указать ник, то под постами и в комментариях будет ваш email)<br>
    <%= f.text_field(:nickname, {:class => 'form-control'}) %>
  </p>

  <p>
    Имя (по желанию)<br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>

  <p>
    Фамилия (по желанию)<br>
    <%= f.text_field(:surname, {:class => 'form-control'}) %>
  </p>

  <p>
    Image<br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-dark'}) %>
  </p>

<% end %>

app/views/users/show.html.erb
<h1>Your profile:</h1>
<% if @user.image? %>
  <%= image_tag @user.image.url(:large), class: 'img-avatar shadow' %>
<% else %>
  <img src="http://i66.tinypic.com/hunnlw.jpg" class="card-img" alt="..." style="max-width: 250px;">
<% end %>
<h5><%= @user.email %></h5>
<h5><%= @user.nickname %></h5>
<h5><%= @user.surname %> <%= @user.name %></h5>

<%= link_to "Edit profile", edit_user_path(@user), :class => 'btn btn-warning' %>

<h1>Your created posts:</h1>

<table class="table">
  <thead class="thead-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Title</th>
    <th scope="col">Created at</th>
    <th scope="col">Some action (update, delete)</th>
  </tr>
  </thead>
  <tbody>
  <% current_user.posts.each_with_index do |post, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= post.title %></td>
      <td><%= post.created_at %></td>
      <td>
        <%= link_to "Edit event", edit_post_path(post), :class => 'btn btn-dark' %>
        <%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Вы уверены, что хотите удалить этот пост?"}, :class => 'btn btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>